version: '2'
services:
  web:
    build: .
    command: ./artisan migrate
    volumes:
      - ./:/var/www/html/laravel/
    ports:
      - "777:80"
    depends_on:
      - db
  db:
    image: "mysql:5.6.27"
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"